export const SET_INIT_STORY_TEXT = "SET_INIT_STORY_TEXT";
export const APPEND_STORY_TEXT = "APPEND_STORY_TEXT";
export const REMOVE_STORY_TEXT = "REMOVE_STORY_TEXT";
export const RESET_STORY_TEXT = "RESET_STORY_TEXT";

export const SET_PROMPT = "SET_PROMPT";

export const SET_LOADING = "SET_LOADING";
