export const CHARACTER_SYMBOL = "${CHARACTER_SYMBOL}";

export const randomPromptsWithCharacters = Object.freeze([
  `Trodding through the snowy forest, ${CHARACTER_SYMBOL} had little reason to suspect anything was amiss. All of a sudden, an old man appeared out of`,
  `Clutching the briefcase tightly, ${CHARACTER_SYMBOL} navigated quickly through the winding corridors of the library in search of an exit. Hot in pursuit of ${CHARACTER_SYMBOL} was`,
  `A hundred million miles from Alpha Centauri, a lone astronaut floated adrift in space. The astronaut, ${CHARACTER_SYMBOL}, had been abandoned there by`,
  `Since a young child, ${CHARACTER_SYMBOL} had dreamed of becoming the President of the United States of America. Now, the day had finally arived when ${CHARACTER_SYMBOL} would`,
  `Baking in the afternoon sun, ${CHARACTER_SYMBOL} lay stretched out on the lawn, watching the clouds pass by. All of a sudden, ${CHARACTER_SYMBOL} spotted something off in the distance getting closer by the minute.`,
  `Down in ${CHARACTER_SYMBOL}'s basement was an assortment of strange implements: fuzzy handcuffs, whips, gag balls, and more. ${CHARACTER_SYMBOL} regularly used these to`,
  `It was the third week of summer camp and ${CHARACTER_SYMBOL} was getting homesick. All of a sudden, he saw something emerging from the lake:`,
  `${CHARACTER_SYMBOL} was sitting on the bench, doing the Sunday crossword. All of a sudden, the words on the paper started moving and rearranging`,
  `As soon as ${CHARACTER_SYMBOL} disembarked from the plane, it began harder and harder to remember certain details of`,
  `After ${CHARACTER_SYMBOL}'s many relationships in the past had all come to tragic conclusions, ${CHARACTER_SYMBOL} decided to turn to`,
  `Due to prohibition, it had become impossible for ${CHARACTER_SYMBOL} to acquire any alcohol. In an act of desperation, ${CHARACTER_SYMBOL} decided to make some `,
  `It was Christmas day, and ${CHARACTER_SYMBOL} was in jolly spirits. All of a sudden, Santa Claus stumbled into his living room, his face smeared in blood and`,
  `${CHARACTER_SYMBOL} was terrified of the schoolyard bully who seemed to make every day miserable. Today, however, ${CHARACTER_SYMBOL} had devised a brilliant plan to rid`,
  `${CHARACTER_SYMBOL} had always been a bully and terrified all the other kids at school mercilessly. One day, the other kids ganged up and`,
  `${CHARACTER_SYMBOL} had never resorted to petty crime before, but now ${CHARACTER_SYMBOL} needed money for crack. So ${CHARACTER_SYMBOL} put on a ski mask, grabbed a glock, and headed to`,
  `It was ${CHARACTER_SYMBOL}'s first time spelunking, and things were going horribly wrong. The entrance to the cave had collapsed and in order to survive, ${CHARACTER_SYMBOL} was going to have to`,
  `As the world's foremost physics researcher, ${CHARACTER_SYMBOL} had finally discovered how to generate a portal to another dimension. ${CHARACTER_SYMBOL} stepped through the portal and`,
  `Although formerly a nonbeliever, ${CHARACTER_SYMBOL} had now seen the light, and had become the leader of`,
  `Hunting sharks was ${CHARACTER_SYMBOL}'s profession and passion in life. ${CHARACTER_SYMBOL} had slain countless sharks, large and small. One day, while out looking for`,
  `${CHARACTER_SYMBOL} had devised a brilliant plan to stop global warming from destroying the planet. The plan was to`,
  `${CHARACTER_SYMBOL} had been having the same recurring nightmare over and over. In the nightmare, ${CHARACTER_SYMBOL} was walking to the grocery store when`,
  `The ski trip was going phenomenally well. ${CHARACTER_SYMBOL} was carving down the slopes, having a merry old time, and looking forward to the rest of the day. Suddenly, Bigfoot`,
  `Given ${CHARACTER_SYMBOL}'s wealth and social status, ${CHARACTER_SYMBOL} would never usually enter a Wal-Mart, but today was an exception. The reason for the exception was`,
  `As the leader of communist China, ${CHARACTER_SYMBOL} had only one mission:`,
  `${CHARACTER_SYMBOL} was known as the fastest gun in the West. An unruly outlaw, without a conscience, ${CHARACTER_SYMBOL} was known for`,
  `After many years of committing identity theft and stealing cars, ${CHARACTER_SYMBOL} finally repented after`,
  `Having had no success wtih dating, ${CHARACTER_SYMBOL} finally agreed to have an arranged marriage. On the wedding day, ${CHARACTER_SYMBOL} was shocked to learn`,
  `${CHARACTER_SYMBOL} was a high powered lawyer, known for ruthlessness and just getting the job done. But ${CHARACTER_SYMBOL} had never truly known the meaning of`,
  `${CHARACTER_SYMBOL} had recently been voted the sexiest person alive, and it was clear why. Nobody could match ${CHARACTER_SYMBOL} in`,
  `Driving drunk, recklessly careening down the highway, ${CHARACTER_SYMBOL} was behind the wheel of a`,
  `Nothing was more important to ${CHARACTER_SYMBOL} than chastity and purity, in the eyes of the Lord. That was until`,
  `On New Years Eve, ${CHARACTER_SYMBOL} risked it all for a single kiss from`,
  `${CHARACTER_SYMBOL} had a horrible secret. ${CHARACTER_SYMBOL} was known as a "furry," which means`,
  `Late at night, ${CHARACTER_SYMBOL} stole across the empty courtyard, taking care to be as silent as possible. In ${CHARACTER_SYMBOL}'s hand was a dagger, gleaming in the moonlight.`,
  `Throughout the land, ${CHARACTER_SYMBOL} was famous for a very odd reason. Knights and Ladies came from far away to look upon ${CHARACTER_SYMBOL}'s massive`,
  `Even though ${CHARACTER_SYMBOL}'s parents were kind, attentive, and caring, ${CHARACTER_SYMBOL} still grew up to be the most`,
  `Although ${CHARACTER_SYMBOL} didn't have any interests, passions, friends, or hobbies, ${CHARACTER_SYMBOL} really loved to`,
  `The career counselor urged ${CHARACTER_SYMBOL} not to go to college, not because ${CHARACTER_SYMBOL} wouldn't be able to handle the academic rigor, but`,
  `As the company's only intern, ${CHARACTER_SYMBOL}'s duties included standard things like fetching coffee and making photocopies. ${CHARACTER_SYMBOL} was surprised to learn that in addition to these duties, ${CHARACTER_SYMBOL} was also given the distasteful assignment of`,
  `${CHARACTER_SYMBOL} hadn't known a pleasure quite like this in years. It felt so good. ${CHARACTER_SYMBOL} couldn't believe this was the first time`,
  `The day of ${CHARACTER_SYMBOL}'s death had finally arrived. ${CHARACTER_SYMBOL} was going to take a cyanide pill and entomb three close friends along with`,
  `${CHARACTER_SYMBOL} was voted the "dumbest person on Earth" after ${CHARACTER_SYMBOL} made the idiotic blunder of`,
  `The ghost of ${CHARACTER_SYMBOL} had been haunting the old building for years. Screeching noises could be heard at all times of night, and strange lights often flashed in the windows. The only thing that could release ${CHARACTER_SYMBOL}'s soul was`,
]);

export const randomPromptsWithoutCharacters = Object.freeze([
  "After the devastating nuclear war of 1986, humanity had retreated into deep underground bunkers for their own safety. Now, in the year 2022, they were finally beginning to emerge.",
  "In the late hours of the night, an impenetrable darkness shrouded the plaza. Suddenly, there was a flash of light, and",
  "Piled up on the interstate was the smoking wreckage of thirteen cars. The road was slick with ice, oil, and blood. Suddenly, from amidst the wreckage emerged",
  "Deep under the sea was a vibrant civilization of mermaids and mermen. Their king was a",
  "A blood-curdling scream issued forth from the dark forest. Moments later, the Easter Bunny hopped of the woods, covered in",
  "Kanye West had finally agreed to take on an intern. His first task for the intern was",
  "Down in the dark, dank dungeon, mice were scurrying across the floor and prisoners were languishing in chains. All of a sudden, the floor began to crack open and",
  "The devil one day decided to abandon his post in Hell. Instead, he decided, he was going to go to New York City and open a",
  "The Pharaoh was furious that his slaves had escaped without finishing construction of the pyramid. In retaliation, he",
  "In the year 2033, the existence of God was disproved via a very simple mathematical proof:",
  "A dog, a priest, and a politician walk into a bar.",
  "After getting disheartened by seeing all his children using TikTok, God decreed that",
  "Down in the cargo hold of the ship, something strange was happening. The boxes were all rattling, and",
]);
